### ISSUE TITLE
Add a job to build the docs on CI

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1063]
This issue is part of the improvements to the CI because we want to move from Appveyor to GitHub actions. One of the improvements includes adding a job to build the docs.

- Move docs dependencies to `requirements-dev.txt`, and delete the docs requirements (too much complexity having two files, for little gain)
- Create a new build in the CI similar to the tests one (install deps, build extension), and run `sphinx-build -W docs/source html` instead of pytest
- Fix any problem in the docs that happens when the above is executed

**Comment by datapythonista** [comment]
All this needs is:

- Move docs dependencies to `requirements-dev.txt`, and delete the docs requirements (too much complexity having two files, for little gain)
- Create a new build in the CI similar to the tests one (install deps, build extension), and run `sphinx-build -W docs/source html` instead of pytest
- Fix any problem in the docs that happens when the above is executed

**Comment by LucyJimenez** [comment]
Thank you, Marc. I'll include it in the description.

**Comment by LucyJimenez** [comment]
I'm going to work on this issue.

**Comment by datapythonista** [comment]
Fixed in #1107
