### ISSUE TITLE
CI: Tests with pypy don't finish

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#1117]
Seems like sometimes when running the test suite with pypy, the tests will take forever. I saw this happening with both versions of pypy in the CI, and the builds took more than 3 or 4 hours until I cancelled them.

You can see an example here: https://github.com/airspeed-velocity/asv/runs/5470152967?check_suite_focus=true

@fangchenli @mattip any idea what could be the problem?

**Comment by mattip** [comment]
A couple of thoughts:
- Is there a stopping condition for the benchmark run that requires the benchmark run time to be stable? Perhaps the JIT is confusing the definition of "stable", since the run times can vary for micro benchmarks. The paper ["Virtual Machine Warmup Blows Hot and Cold"](https://arxiv.org/abs/1602.00602) describes the phenomenon . Can the stopping condition be controlled?
- Each benchmarks should have a timeout, especially for unit tests of the asv code. Perhaps all the tests should inherit from a class with a default timeout?
- The overall CI should have a [timeout](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes). The default is 360 minutes, which is way too long.[here](https://github.com/python-pillow/Pillow/blob/397a9409959bccd0130d0b51820f2a94e3bf153d/.github/workflows/test-windows.yml#L20) is an example from the Pillow project
