### ISSUE TITLE
Support snakeviz

### ISSUE THREAD

**Issue by cdeil** [airspeed-velocity/asv#183]
It would be great if `asv` supported https://github.com/jiffyclub/snakeviz in addition to `RunSnakeRun`,
because it's easy to install anywhere (e.g. on Mac).

Long-term using a web-profile-viewer might allow interactivity by making a webapp: click on one or two commits, click "profile" ... asv goes off and executes the commands and opens a new browser window with the results.

cc @jiffyclub

**Comment by mdboom** [comment]
Yes, as a first pass, we could support snakeviz as just another profiling GUI alongside the desktop ones `asv` already supports.

The long term plan is to save the profiling data along with the benchmarking results and be able to get to them directly from the `asv` ui.  There's a couple of obstacles to this: Python cProfile data doesn't contain the source code -- only hardcoded paths to the source code -- so this would have to be converted to something static that did contain the source code so that sharing profiling data across machines/users made sense.  Secondly, `snakeviz` probably isn't the appropriate tool for this as it stands now, since it includes a server-side component.  It may be not be a huge step to modify it to run off of static data, however -- that would be ideal, then it just becomes another part of the static blob that gets placed on a static web server.

**Comment by cdeil** [comment]
Or `asv` grows an optional server-side components in addition to it's current capability of creating static webpages. IMO having the ability to browse benchmarks and then to profile and try to understand the "interesting" features they show easily would be super nice.

**Comment by jiffyclub** [comment]
SnakeViz is fairly amenable to this since it's turning into a static, single-page application. The server does do some pre-processing of the stats, but once it's done it renders/delivers the HTML and then the server's job is over (except to deliver static assets). If you can generate and store that rendered HTML you're on your way (I haven't looked into how to do this). You'd also have to make sure SnakeViz's static assets were on the server.

**Comment by mdboom** [comment]
Yes, but the fact that `asv` has no server-side component is the whole reason I started the project, since none of the available alternatives work that way.  I think a lot would be lost if we moved away from that.  I'm not sure that snakeviz really needs the server side component, except that it was a convenient way to develop it.

**Comment by mdboom** [comment]
@jiffyclub: I think our comments just crossed lines.  That sounds promising that there's a possible way to do this statically.

**Comment by astafan8** [comment]
snakeviz is supported so thia issue can be closed ;)
