### ISSUE TITLE
Allow conda environment specification from enviroment.yml file(s)

### ISSUE THREAD

**Issue by jni** [airspeed-velocity/asv#372]
Conda already provides a dependency management option in the environment.yml file. I recently added one for my project in addition to the existing requirements.txt for pip. As I'm starting out with asv, I'm dismayed to find out that I need to specify my dependencies at yet another place.

This feature would enable:
- not having one more place to remember to update when requirements are bumped up.
- allowing PyPI packages in conda environments, which is not currently possible with asv.

**Comment by andyfaff** [comment]
+1 for this. At the moment I am trying to benchmark a project that has an optional dependency that is only installable by pip. The optional dependency does not get installed automatically by the setup.py of the project. I tried specifying the dependency using the `matrix` section in `asv.conf.json`. However, the dependency failed to install because the projects `environment_type` is `conda`.

Could we used the `--python` flag, or a `--environment` flag to specify a conda environment.yml file, as produced by `conda env export` to specify such dependencies?

**Comment by andyfaff** [comment]
I'd have a go at trying to work on this, but I wouldn't know where to start in the codebase.

**Comment by pv** [comment]
asv/plugins/conda.py, asv/config.py are relevant. Did not yet think
about this feature, though.

**Comment by mdboom** [comment]
:+1: on the idea.  The downside is that the ability to generate a matrix of dependencies goes away, or at least is less convenient.  How would you propose having different configurations?  Multiple environment.yml files?

**Comment by jni** [comment]
@mdboom Thanks for the support! =) Two suggestions:

1. multiple .yml files, as you suggest, or
2. .yml + overriding of the .yml by additional entries to the build matrix.

**Comment by andyfaff** [comment]
The reason I suggested conda environment files was because I needed to
install some optional dependencies via pip (not available via conda). The
project wanted to use conda as the environment type, so I had no way of
installing those dependencies. However, #373 fixes this issue. Therefore,
my original need for conda environment files disappeared.

**Comment by jni** [comment]
@andyfaff Thanks for your contribution! That definitely gets me unstuck in the short term! In the longer term, your PR addresses motivation 2 of this request, but not motivation 1, which is to limit the number of places needing to document dependencies.

**Comment by jmemich** [comment]
Adding another +1 here. I'm in the same boat as the OP. 

Additionally, however, I have use case where my project has an environment.yml file which grabs dependencies from github at a specific commit (i.e., `git+https://github.com/project/project.git@abcdefgh123456789`) and currently it's not possible to benchmark the parts of my project which depend on this dependency.

Would patching up [`conda.py`](https://github.com/spacetelescope/asv/blob/master/asv/plugins/conda.py#L102-L112) to look to look for a `+git` prefix be workable / acceptable?

**Comment by andyfaff** [comment]
Master branch now allows you to specify pip only packages in the install
matrix

**Comment by jmemich** [comment]
I just checked and `pip+git+https://github.com/...` works. Thanks!

**Comment by mortada** [comment]
I'm starting to use `asv` and I'd really like to have this feature as well, would be very useful for `asv` to support `environment.yml`
