### ISSUE TITLE
import _from_ benchmark.py allowed

### ISSUE THREAD

**Issue by jbrockmendel** [airspeed-velocity/asv#656]
benchmark.py has a prominent comment saying it cannot import anything outside the standard library.  But is it OK to go the other direction and import _from_ benchmark.py?

I'm toying with ways to make discovery less subprocess-y, more API-y (related #413) and being able to do this import would help.

**Comment by pv** [comment]
Yes, I suppose you can import things from `benchmark.py` in asv at least. However, I don't see the how gh-413 is related so maybe you can unpack this a bit.

Note that I'm not that convinced it is useful to spend time on refactoring to remove the subprocess barrier in benchmark discovery. The discovery process needs to run as a subprocess as it may need to import the built library, and the simplest IPC is via files stored on the filesystem.

Of course, benchmark discovery could in principle be more declarative in that it wouldn't need to execute Python code (and then more refactoring could be done), but I think that ship may have sailed for asv --- at least it would be quite disruptive change.

**Comment by jbrockmendel** [comment]
> Yes, I suppose you can import things from `benchmark.py` in asv at least.

My first attempt at this caused a test failure in `test_find_benchmarks_cwd_imports` with error message "ImportError: No module named test".  I need to look into it more closely, am guessing that edits to `sys.path` were relevant.

> However, I don't see the how gh-413 is related so maybe you can unpack this a bit.

The relationship is vague, mostly that I'd like to be able to do something like:

```
import asv
benchs = asv.find_benchmarks(some_config_info)
res = benchs[4].run(n=4, target_time=18.4, **kwargs)
```

> Of course, benchmark discovery could in principle be more declarative [...] at least it would be quite disruptive change.

To an extent refactoring locally is part of my process for wrapping my head around new code.  Separating out discovery was an attempt to isolate the benchmark-running so I could get a better handle on that.

The over-arching goal I'm hoping to make progress on is improving stability on very-fast benchmarks for dateutil and pandas.  The three medium-term ideas I have in mind are:

- interleave runs between commits to smooth out background noise
- make it easy to jack up the sample size
- make it possible to aggregate results across runs (i.e. increase sample size by running multiple times)

I guess before I spend too much time on these I should ask: are you amenable to (any of) them?

**Comment by pv** [comment]
Ok, yes --- for programmatic use, you can look how the tests do it. This is however quite more verbose than the above, as you typically need to provide the Config object and some of the logic is in the commands rather than in ASV core. There's probably room for refactoring the logic out from the commands in to the core.

For the interleaving issue, I guess gh-647 is my take on it. In order to disentangle setup_cache logic, running commands, and printing output I refactored it to a system first construcing and then running a list of Jobs (improvement suggestions / review on this PR would be welcome). 

The per-commit running is however not refactored out in the Run command --- doing that is probably reasonably straightforward, and could be one extension to this. (Aggregation of results across multiple runs is integrated in gh-647.)

Another thing I had in mind, especially relevant for pandas, is to add a "forkserver" runner to avoid getting hit by the Python startup and library import time issues. (Which is important when "python -c 'import pandas'" takes 3 seconds.)
