### ISSUE TITLE
'asv run' fails on import

### ISSUE THREAD

**Issue by Moisan** [airspeed-velocity/asv#805]
When trying to setup asv on my project, it fails to import the project in any benchmark file when running `asv run`. Here is an example how to reproduce with an open-source project (`requests`):
```
git clone https://github.com/kennethreitz/requests.git
cd requests
asv quickstart
<choose option 1>
<add `import requests` to the top of benchmarks/benchmarks.py>
asv run
```
This ends up with the error `ModuleNotFoundError: No module named 'requests'`. However when launching the created python env in `.asv/env`, `import requests` doesn't lead to any error. What am I missing?

**Comment by pv** [comment]
I get
```
~/tmp/xxx/requests$ cd .asv
~/tmp/xxx/requests/.asv$ ./env/a80b4bcff004e7d21aafa78a5932418b/bin/python
Python 3.7.3 (default, Mar 27 2019, 13:36:35) 
[GCC 9.0.1 20190227 (Red Hat 9.0.1-0.8)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```
The import succeeds without the "cd" because the requests module is in the current directory then.

Apparently, this also causes pip to refuse to install the built requests wheel into the environment.
Workaround is to set in asv.conf.json,
`"install_command": ["python -mpip install --force-reinstall {wheel_file}"],`

Probably that flag should be there by default.
