### ISSUE TITLE
regressions: set proper regression range

### ISSUE THREAD

**Issue by pared** [airspeed-velocity/asv#933]
Following test:
```
def test_regression_threshold_custom():
    steps = [(0, 1,   1.0, 1.0, 0.0),
             (1, 2,   2, 2, 0.0),
             (2, 3,   1.5, 1.5, 0.0),]

    latest, best, pos = detect_regressions(steps, threshold=0.05)
    assert pos == [(0, 1, 1.0, 1.5)]
```
passes. I Think the proper result should be `[(0, 2, 1.0, 1.5)]`

Not sure how rendering side of `asv publish` would handle that.

**Comment by pv** [comment]
I think it works as expected: the `threshold` is a *minimum* threshold but the increase still needs to be statistically detectable, for which three data points is not sufficient.

**Comment by pared** [comment]
@pv got it. It seems reasonable to point only "first step". Though in visualization we end up with regression report that reports
different changes than display. What I mean here, i prepared artificial benchmark that just changes execution time 10ms -> 20ms -> 15ms and we get:
![regression](https://user-images.githubusercontent.com/10195618/85055585-109e9980-b19e-11ea-8ff1-af2837c708ae.png)

While the regression plot looks like this:
![regression_plot](https://user-images.githubusercontent.com/10195618/85055660-2d3ad180-b19e-11ea-8bf4-524040a5119a.png)

Can it stay that way? If not, what would be the desired behavior in that case?

**Comment by pv** [comment]
The practical reason is that for the regressions, what you are usually mainly interested in is how much the latest result is worse than some previous value. The size of the individual upsteps is not informative and e.g. sorting by them is misleading, since bad regressions usually are fixed and followed by a downstep that might end up slightly above the value before. To deal with this, it's more informative to see the badness of the regression by comparing to the best value after it. Since there's no way to know the causal relationship between the steps, some compromise in the visualization has to be made and I think how it works now is useful.

So I think the fix here would be to rename the "After" column header to something more descriptive.
