### ISSUE TITLE
Another representation for ratio column when benchmarking

### ISSUE THREAD

**Issue by YarShev** [airspeed-velocity/asv#952]
Hi there,

After I tried `asv` for my needs, I saw that `ratio` column is relation `after` to `before` (I mean `ratio=after/before`) based on the output:
```bash
       before           after         ratio
     [74587461]       [0c9b56d0]
     <master>         <internal-error>
!        62910ms           failed      n/a  benchmarks.TimeBinaryOp.time_concat('int', (10128, 100, 10000, 128), 'mul', 1)
-         2663ms          1332ms     0.50  benchmarks.TimeConcat.time_concat('int', (10128, 100, 10000, 128), 'inner', 1)
-      1.130.01s          1415ms     0.12  benchmarks.TimeConcat.time_concat('int', (10128, 100, 10000, 128), 'inner', 0)
```
I think it's better to use `ratio=before/after` in order to showcase speed up or slowdown for an operation. At least wherever I saw `ratio=before/after` notation is used. Is it possible to change representation of `ratio` column?

Thanks in advance for attention!

**Comment by HaoZeke** [comment]
I think there's no real good answer to this, other than that the conventions are now documented better #1421. It isn't always before after, it could just be commit1 and altcommit1 and swapping them in the CLI would give the conventional view point as well. A PR would be the next step for a discussion on this, especially since the mark parameter is currently a bit overloaded in terms of ' '.
